i18n:
 console_lang: EN_US

network:
 port: 80

statistics:

mixin:
  fix_explosion: false
  sand_duping: false

vote:
  vote_op_absolute_disagreement: true

world:
  chunkforcer:
    minecraft:nether:
    minecraft:the_end:
    minecraft:overworld: