i18n:
 console: EN_US
 players:
   88888888-8888-8888-8888-888888888888: EN_US

network:
 port: 80

statistics:


mixin:
  fix_explosion: false
  sand_duping: false

vote:
  vote_op_absolute_disagreement: true

world:
  chunkforcer:
    minecraft:nether:
    minecraft:the_end:
    minecraft:overworld: